Displayed image and added mouse and key listener
daniel-falk/playerpy pull request #2
Opened 2021-07-04 21:05 UTC by keldavis

2021-07-05 21:48 UTC, daniel-falk requested changes
I like the result, it works great. See comments for some minor things.

2021-07-05 21:48 UTC, daniel-falk commented on web/server.py
> +        Display closed address and send image path
Incorrect comment: no image path sent in handle_close

2021-07-05 21:48 UTC, daniel-falk commented on web/test.html
> +    if (e.code === "ArrowLeft") {
Can we change line 44-50 to simply forward all key events, then we can filter in the back end instead. We could also try to be consistent in the format with the mouse click events:

doSend("EVENT(key)=" + e.code)

2021-07-05 21:48 UTC, daniel-falk commented on web/test.html
> +    if (!evt) var evt = window.event;
A comment would be nice explaining when evt is injected as the argument and when we need to get is from the window object

2021-07-05 21:48 UTC, daniel-falk commented on web/test.html
> +    if (evt.pageX || evt.pageY) {
Add a comment explaining why we need to check both pageX and clientX, browser dependent or dependent on what we click on?

2021-07-05 21:48 UTC, daniel-falk commented on web/test.html
> +    doSend("COORDINATES(x,y)=(" + x + "," + y+")")
considering the function name "getImageCoordinates" it is a bit confusing that it does not return anything but instead sends the result to the back end. Perhaps we could add a new function:

function sendImageClickCoordinates(evt) {
    var coords = getImageCoordinates(evt)
    doSend("COORDINATES(x,y)=(" + coords.x + "," + coords.y+")")
}

2021-07-05 21:48 UTC, daniel-falk commented on web/test.html
> +  //Getting reference of image
This comment is a bit redundant - comments should normally tell why you do something, not what you do (that's clear from the code itself). E.g.:

// Attach mouse event to image to send the clicked coordinates to the back end
var img = document.getElementById("image");
img.onmousedown = GetImageCoordinates;

2021-07-17 03:26 UTC, keldavis commented
Hi,

I sent the pull request a while back. 

Kelli Davis

Sent from my iPhone

> On Jul 5, 2021, at 5:48 PM, Daniel Falk ***@***.***> wrote:
> 
> ﻿
> @daniel-falk requested changes on this pull request.
> 
> I like the result, it works great. See comments for some minor things.
> 
> In web/server.py:
> 
> > -    """Advance every image source one frame per 3 seconds
> -    """
> -    while True:
> -        for _, image_source in server.connections.items():
> -            image_source.idx += 1
> -            image_source.send_image_path()
> -        time.sleep(10)
> -
> -server = WebSocketServer('', 8000, SimpleImageSource)
> -th = threading.Thread(target=advance_loop, args=(server,), daemon=True)
> -th.start()
> -server.serve_forever()
> +from simple_websocket_server import WebSocketServer, WebSocket
> +import threading
> +import time
> +import re
> Unused import re
> 
> In web/server.py:
> 
> > -
> -
> -def advance_loop(server):
> -    """Advance every image source one frame per 3 seconds
> -    """
> -    while True:
> -        for _, image_source in server.connections.items():
> -            image_source.idx += 1
> -            image_source.send_image_path()
> -        time.sleep(10)
> -
> -server = WebSocketServer('', 8000, SimpleImageSource)
> -th = threading.Thread(target=advance_loop, args=(server,), daemon=True)
> -th.start()
> -server.serve_forever()
> +from simple_websocket_server import WebSocketServer, WebSocket
> The files are saved using dos-styled new lines, while the files in its original are unix styled new lines. This cause the diff view in github to fail. You can probably set your editor to save with unix style line endings, e.g. in visual studio: File > Advanced Save Options, select Unix Line Endings.
> 
> In web/server.py:
> 
> > +            return
> +        else:
> +            print("Unknown event: %s" % str(self.data))
> +            return
> +        self.send_image_path()
> +
> +    def connected(self):
> +        """
> +        Display connected address and send image path
> +        """
> +        print(self.address, 'connected')
> +        self.send_image_path()
> +
> +    def handle_close(self):
> +        """
> +        Display closed address and send image path
> Incorrect comment: no image path sent in handle_close
> 
> In web/test.html:
> 
> > +    max-width: 48%;
> +    position: absolute;
> +    border: 1px solid black;
> +
> +  }
> +</style>
> +
> +
> +<script language="javascript" type="text/javascript">
> +
> +  //add event listener for page load
> +  window.addEventListener("load", init, false);
> +
> +  //add event listener for key press
> +  document.addEventListener('keyup', (e) => {
> +    if (e.code === "ArrowLeft") {
> Can we change line 44-50 to simply forward all key events, then we can filter in the back end instead. We could also try to be consistent in the format with the mouse click events:
> 
> doSend("EVENT(key)=" + e.code)
> 
> In web/test.html:
> 
> > +        y += img.offsetTop;
> +      }
> +      return [x, y];
> +    }
> +    else {
> +      return [img.x, img.y];
> +    }
> +  }
> +
> +  //Function to get normalize coordinates of image
> +  function GetImageCoordinates(evt) {
> +    var x = 0;
> +    var y = 0;
> +    var imgPos;
> +    imgPos = findImagePosition(img);
> +    if (!evt) var evt = window.event;
> A comment would be nice explaining when evt is injected as the argument and when we need to get is from the window object
> 
> In web/test.html:
> 
> > +      }
> +      return [x, y];
> +    }
> +    else {
> +      return [img.x, img.y];
> +    }
> +  }
> +
> +  //Function to get normalize coordinates of image
> +  function GetImageCoordinates(evt) {
> +    var x = 0;
> +    var y = 0;
> +    var imgPos;
> +    imgPos = findImagePosition(img);
> +    if (!evt) var evt = window.event;
> +    if (evt.pageX || evt.pageY) {
> Add a comment explaining why we need to check both pageX and clientX, browser dependent or dependent on what we click on?
> 
> In web/test.html:
> 
> > +      x = 0;
> +    }
> +    else if (x > img.width) {
> +      x = img.width
> +    }
> +    x /= img.width;
> +
> +    y -= imgPos[1]
> +    if (y < 0) {
> +      y = 0;
> +    }
> +    else if (y > img.height) {
> +      y = img.height
> +    }
> +    y /= img.height;
> +    doSend("COORDINATES(x,y)=(" + x + "," + y+")")
> considering the function name "getImageCoordinates" it is a bit confusing that it does not return anything but instead sends the result to the back end. Perhaps we could add a new function:
> 
> function sendImageClickCoordinates(evt) {
> var coords = getImageCoordinates(evt)
> doSend("COORDINATES(x,y)=(" + coords.x + "," + coords.y+")")
> }
> 
> In web/test.html:
> 
> > +    </div>
> +    <div class="column">
> +      <textarea name="outputtext" rows="20" cols="50"></textarea>
> +      <textarea name="inputtext" cols="50"></textarea>
> +      <textarea name="url" cols="50"></textarea>
> +      <br>
> +      <input type="button" name=sendButton value="Send" onClick="sendText();">
> +      <input type="button" name=clearButton value="Clear" onClick="clearText();">
> +      <input type="button" name=disconnectButton value="Disconnect" onClick="doDisconnect();">
> +      <input type="button" name=connectButton value="Connect" onClick="doConnect();">
> +      </p>
> +    </div>
> +  </div>
> +</form>
> +<script>
> +  //Getting reference of image
> This comment is a bit redundant - comments should normally tell why you do something, not what you do (that's clear from the code itself). E.g.:
> 
> // Attach mouse event to image to send the clicked coordinates to the back end
> var img = document.getElementById("image");
> img.onmousedown = GetImageCoordinates;
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-18 16:08 UTC, daniel-falk approved these changes
Excellent, I'll merge this to the feature branch. Thanks Kelli!

2021-07-18 16:09 UTC, merged